<?php
/**
 * Created by PhpStorm.
 * User: Nguyen Tuan Linh
 * Date: 2015-12-06
 * Time: 19:13
 */

return [
    'settings' => [
        'city' => 'LA',
        'country' => 'US',
        'currency' => 'USD',
        'number_format' => 'point_comma',
        'first_day_of_week' => 0,
        'long_date_format' => 0,
        'short_date_format' => 0,
        'long_time_format' => 0,
        'short_time_format' => 0,
    ],

    'idle_switching_time' => 120, // seconds

    'admin_theme' => Katniss\Everdeen\Themes\AdminThemes\AdminLte\Theme::NAME,
    'home_theme' => Katniss\Everdeen\Themes\HomeThemes\DefaultTheme\Theme::NAME,
    'admin_themes' => [
        Katniss\Everdeen\Themes\AdminThemes\AdminLte\Theme::NAME => Katniss\Everdeen\Themes\AdminThemes\AdminLte\Theme::class,
    ],
    'home_themes' => [
        Katniss\Everdeen\Themes\HomeThemes\DefaultTheme\Theme::NAME => Katniss\Everdeen\Themes\HomeThemes\DefaultTheme\Theme::class,
    ],
    'widgets' => [
        Katniss\Everdeen\Themes\Plugins\ExtraHtml\Widget::NAME => Katniss\Everdeen\Themes\Plugins\ExtraHtml\Widget::class,
        Katniss\Everdeen\Themes\Plugins\BaseLinks\Widget::NAME => Katniss\Everdeen\Themes\Plugins\BaseLinks\Widget::class,
    ],
    'extensions' => [
        Katniss\Everdeen\Themes\Plugins\AppSettings\Extension::NAME => Katniss\Everdeen\Themes\Plugins\AppSettings\Extension::class,
        Katniss\Everdeen\Themes\Plugins\OpenGraphTags\Extension::NAME => Katniss\Everdeen\Themes\Plugins\OpenGraphTags\Extension::class,
        Katniss\Everdeen\Themes\Plugins\AnalyticServices\Extension::NAME => Katniss\Everdeen\Themes\Plugins\AnalyticServices\Extension::class,
        Katniss\Everdeen\Themes\Plugins\SocialIntegration\Extension::NAME => Katniss\Everdeen\Themes\Plugins\SocialIntegration\Extension::class,
        Katniss\Everdeen\Themes\Plugins\CurrencyExchange\Extension::NAME => Katniss\Everdeen\Themes\Plugins\CurrencyExchange\Extension::class,
    ],
    'static_extensions' => [
        Katniss\Everdeen\Themes\Plugins\AppSettings\Extension::NAME,
        Katniss\Everdeen\Themes\Plugins\OpenGraphTags\Extension::NAME,
    ],
    'admin_except_extensions' => [
        Katniss\Everdeen\Themes\Plugins\OpenGraphTags\Extension::NAME,
        Katniss\Everdeen\Themes\Plugins\AnalyticServices\Extension::NAME,
    ],
    'paths_use_admin_theme' => [
        'admin', 'auth', 'documents', 'password', 'me'
    ],

    'genders' => [
        'male', 'female', 'other'
    ],

    'number_formats' => [
        'point_comma',
        'point_space',
        'comma_point',
        'comma_space',
    ],

    'currencies' => [
        'USD' => ['name' => 'U.S. Dollar', 'symbol' => '$'],
        'VND' => ['name' => 'Vietnam Dong', 'symbol' => '₫'],
    ],

    'locales' => [
        'ace' => ['name' => 'Achinese', 'script' => 'Latn', 'native' => 'Aceh'],
        'af' => ['name' => 'Afrikaans', 'script' => 'Latn', 'native' => 'Afrikaans'],
        'agq' => ['name' => 'Aghem', 'script' => 'Latn', 'native' => 'Aghem'],
        'ak' => ['name' => 'Akan', 'script' => 'Latn', 'native' => 'Akan'],
        'an' => ['name' => 'Aragonese', 'script' => 'Latn', 'native' => 'Aragonés'],
        'cch' => ['name' => 'Atsam', 'script' => 'Latn', 'native' => 'Atsam'],
        'gn' => ['name' => 'Guaraní', 'script' => 'Latn', 'native' => 'Avañe’ẽ'],
        'ae' => ['name' => 'Avestan', 'script' => 'Latn', 'native' => 'Avesta'],
        'ay' => ['name' => 'Aymara', 'script' => 'Latn', 'native' => 'Aymar aru'],
        'az' => ['name' => 'Azerbaijani (Latin)', 'script' => 'Latn', 'native' => 'Azərbaycanca'],
        'id' => ['name' => 'Indonesian', 'script' => 'Latn', 'native' => 'Bahasa Indonesia'],
        'ms' => ['name' => 'Malay', 'script' => 'Latn', 'native' => 'Bahasa Melayu'],
        'bm' => ['name' => 'Bambara', 'script' => 'Latn', 'native' => 'Bamanakan'],
        'jv' => ['name' => 'Javanese (Latin)', 'script' => 'Latn', 'native' => 'Basa Jawa'],
        'su' => ['name' => 'Sundanese', 'script' => 'Latn', 'native' => 'Basa Sunda'],
        'bh' => ['name' => 'Bihari', 'script' => 'Latn', 'native' => 'Bihari'],
        'bi' => ['name' => 'Bislama', 'script' => 'Latn', 'native' => 'Bislama'],
        'nb' => ['name' => 'Norwegian Bokmål', 'script' => 'Latn', 'native' => 'Bokmål'],
        'bs' => ['name' => 'Bosnian', 'script' => 'Latn', 'native' => 'Bosanski'],
        'br' => ['name' => 'Breton', 'script' => 'Latn', 'native' => 'Brezhoneg'],
        'ca' => ['name' => 'Catalan', 'script' => 'Latn', 'native' => 'Català'],
        'ch' => ['name' => 'Chamorro', 'script' => 'Latn', 'native' => 'Chamoru'],
        'ny' => ['name' => 'Chewa', 'script' => 'Latn', 'native' => 'ChiCheŵa'],
        'kde' => ['name' => 'Makonde', 'script' => 'Latn', 'native' => 'Chimakonde'],
        'sn' => ['name' => 'Shona', 'script' => 'Latn', 'native' => 'ChiShona'],
        'co' => ['name' => 'Corsican', 'script' => 'Latn', 'native' => 'Corsu'],
        'cy' => ['name' => 'Welsh', 'script' => 'Latn', 'native' => 'Cymraeg'],
        'da' => ['name' => 'Danish', 'script' => 'Latn', 'native' => 'Dansk'],
        'se' => ['name' => 'Northern Sami', 'script' => 'Latn', 'native' => 'Davvisámegiella'],
        'de' => ['name' => 'German', 'script' => 'Latn', 'native' => 'Deutsch'],
        'luo' => ['name' => 'Luo', 'script' => 'Latn', 'native' => 'Dholuo'],
        'nv' => ['name' => 'Navajo', 'script' => 'Latn', 'native' => 'Diné bizaad'],
        'dua' => ['name' => 'Duala', 'script' => 'Latn', 'native' => 'Duálá'],
        'et' => ['name' => 'Estonian', 'script' => 'Latn', 'native' => 'Eesti'],
        'na' => ['name' => 'Nauru', 'script' => 'Latn', 'native' => 'Ekakairũ Naoero'],
        'guz' => ['name' => 'Ekegusii', 'script' => 'Latn', 'native' => 'Ekegusii'],
        'en' => ['name' => 'English', 'script' => 'Latn', 'native' => 'English', 'country_code' => 'US'],
        'en-AU' => ['name' => 'Australian English', 'script' => 'Latn', 'native' => 'Australian English'],
        'en-GB' => ['name' => 'British English', 'script' => 'Latn', 'native' => 'British English'],
        'en-US' => ['name' => 'U.S. English', 'script' => 'Latn', 'native' => 'U.S. English'],
        'es' => ['name' => 'Spanish', 'script' => 'Latn', 'native' => 'Español'],
        'eo' => ['name' => 'Esperanto', 'script' => 'Latn', 'native' => 'Esperanto'],
        'eu' => ['name' => 'Basque', 'script' => 'Latn', 'native' => 'Euskara'],
        'ewo' => ['name' => 'Ewondo', 'script' => 'Latn', 'native' => 'Ewondo'],
        'ee' => ['name' => 'Ewe', 'script' => 'Latn', 'native' => 'Eʋegbe'],
        'fil' => ['name' => 'Filipino', 'script' => 'Latn', 'native' => 'Filipino'],
        'fr' => ['name' => 'French', 'script' => 'Latn', 'native' => 'Français'],
        'fr-CA' => ['name' => 'Canadian French', 'script' => 'Latn', 'native' => 'Français canadien'],
        'fy' => ['name' => 'Western Frisian', 'script' => 'Latn', 'native' => 'Frysk'],
        'fur' => ['name' => 'Friulian', 'script' => 'Latn', 'native' => 'Furlan'],
        'fo' => ['name' => 'Faroese', 'script' => 'Latn', 'native' => 'Føroyskt'],
        'gaa' => ['name' => 'Ga', 'script' => 'Latn', 'native' => 'Ga'],
        'ga' => ['name' => 'Irish', 'script' => 'Latn', 'native' => 'Gaeilge'],
        'gv' => ['name' => 'Manx', 'script' => 'Latn', 'native' => 'Gaelg'],
        'sm' => ['name' => 'Samoan', 'script' => 'Latn', 'native' => 'Gagana fa’a Sāmoa'],
        'gl' => ['name' => 'Galician', 'script' => 'Latn', 'native' => 'Galego'],
        'ki' => ['name' => 'Kikuyu', 'script' => 'Latn', 'native' => 'Gikuyu'],
        'gd' => ['name' => 'Scottish Gaelic', 'script' => 'Latn', 'native' => 'Gàidhlig'],
        'ha' => ['name' => 'Hausa', 'script' => 'Latn', 'native' => 'Hausa'],
        'bez' => ['name' => 'Bena', 'script' => 'Latn', 'native' => 'Hibena'],
        'ho' => ['name' => 'Hiri Motu', 'script' => 'Latn', 'native' => 'Hiri Motu'],
        'hr' => ['name' => 'Croatian', 'script' => 'Latn', 'native' => 'Hrvatski'],
        'bem' => ['name' => 'Bemba', 'script' => 'Latn', 'native' => 'Ichibemba'],
        'io' => ['name' => 'Ido', 'script' => 'Latn', 'native' => 'Ido'],
        'ig' => ['name' => 'Igbo', 'script' => 'Latn', 'native' => 'Igbo'],
        'rn' => ['name' => 'Rundi', 'script' => 'Latn', 'native' => 'Ikirundi'],
        'ia' => ['name' => 'Interlingua', 'script' => 'Latn', 'native' => 'Interlingua'],
        'iu-Latn' => ['name' => 'Inuktitut (Latin)', 'script' => 'Latn', 'native' => 'Inuktitut'],
        'sbp' => ['name' => 'Sileibi', 'script' => 'Latn', 'native' => 'Ishisangu'],
        'nd' => ['name' => 'North Ndebele', 'script' => 'Latn', 'native' => 'IsiNdebele'],
        'nr' => ['name' => 'South Ndebele', 'script' => 'Latn', 'native' => 'IsiNdebele'],
        'xh' => ['name' => 'Xhosa', 'script' => 'Latn', 'native' => 'IsiXhosa'],
        'zu' => ['name' => 'Zulu', 'script' => 'Latn', 'native' => 'IsiZulu'],
        'it' => ['name' => 'Italian', 'script' => 'Latn', 'native' => 'Italiano'],
        'ik' => ['name' => 'Inupiaq', 'script' => 'Latn', 'native' => 'Iñupiaq'],
        'dyo' => ['name' => 'Jola-Fonyi', 'script' => 'Latn', 'native' => 'Joola'],
        'kea' => ['name' => 'Kabuverdianu', 'script' => 'Latn', 'native' => 'Kabuverdianu'],
        'kaj' => ['name' => 'Jju', 'script' => 'Latn', 'native' => 'Kaje'],
        'mh' => ['name' => 'Marshallese', 'script' => 'Latn', 'native' => 'Kajin M̧ajeļ'],
        'kl' => ['name' => 'Kalaallisut', 'script' => 'Latn', 'native' => 'kalaallisut'],
        'kln' => ['name' => 'Kalenjin', 'script' => 'Latn', 'native' => 'Kalenjin'],
        'kr' => ['name' => 'Kanuri', 'script' => 'Latn', 'native' => 'Kanuri'],
        'kcg' => ['name' => 'Tyap', 'script' => 'Latn', 'native' => 'Katab'],
        'kw' => ['name' => 'Cornish', 'script' => 'Latn', 'native' => 'Kernewek'],
        'naq' => ['name' => 'Nama', 'script' => 'Latn', 'native' => 'Khoekhoegowab'],
        'rof' => ['name' => 'Rombo', 'script' => 'Latn', 'native' => 'Kihorombo'],
        'kam' => ['name' => 'Kamba', 'script' => 'Latn', 'native' => 'Kikamba'],
        'kg' => ['name' => 'Kongo', 'script' => 'Latn', 'native' => 'Kikongo'],
        'jmc' => ['name' => 'Machame', 'script' => 'Latn', 'native' => 'Kimachame'],
        'rw' => ['name' => 'Kinyarwanda', 'script' => 'Latn', 'native' => 'Kinyarwanda'],
        'asa' => ['name' => 'Kipare', 'script' => 'Latn', 'native' => 'Kipare'],
        'rwk' => ['name' => 'Rwa', 'script' => 'Latn', 'native' => 'Kiruwa'],
        'saq' => ['name' => 'Samburu', 'script' => 'Latn', 'native' => 'Kisampur'],
        'ksb' => ['name' => 'Shambala', 'script' => 'Latn', 'native' => 'Kishambaa'],
        'swc' => ['name' => 'Congo Swahili', 'script' => 'Latn', 'native' => 'Kiswahili ya Kongo'],
        'sw' => ['name' => 'Swahili', 'script' => 'Latn', 'native' => 'Kiswahili'],
        'dav' => ['name' => 'Dawida', 'script' => 'Latn', 'native' => 'Kitaita'],
        'teo' => ['name' => 'Teso', 'script' => 'Latn', 'native' => 'Kiteso'],
        'khq' => ['name' => 'Koyra Chiini', 'script' => 'Latn', 'native' => 'Koyra ciini'],
        'ses' => ['name' => 'Songhay', 'script' => 'Latn', 'native' => 'Koyraboro senni'],
        'mfe' => ['name' => 'Morisyen', 'script' => 'Latn', 'native' => 'kreol morisien'],
        'ht' => ['name' => 'Haitian', 'script' => 'Latn', 'native' => 'Kreyòl ayisyen'],
        'kj' => ['name' => 'Kuanyama', 'script' => 'Latn', 'native' => 'Kwanyama'],
        'ksh' => ['name' => 'Kölsch', 'script' => 'Latn', 'native' => 'Kölsch'],
        'ebu' => ['name' => 'Kiembu', 'script' => 'Latn', 'native' => 'Kĩembu'],
        'mer' => ['name' => 'Kimîîru', 'script' => 'Latn', 'native' => 'Kĩmĩrũ'],
        'lag' => ['name' => 'Langi', 'script' => 'Latn', 'native' => 'Kɨlaangi'],
        'lah' => ['name' => 'Lahnda', 'script' => 'Latn', 'native' => 'Lahnda'],
        'la' => ['name' => 'Latin', 'script' => 'Latn', 'native' => 'Latine'],
        'lv' => ['name' => 'Latvian', 'script' => 'Latn', 'native' => 'Latviešu'],
        'to' => ['name' => 'Tongan', 'script' => 'Latn', 'native' => 'Lea fakatonga'],
        'lt' => ['name' => 'Lithuanian', 'script' => 'Latn', 'native' => 'Lietuvių'],
        'li' => ['name' => 'Limburgish', 'script' => 'Latn', 'native' => 'Limburgs'],
        'ln' => ['name' => 'Lingala', 'script' => 'Latn', 'native' => 'Lingála'],
        'lg' => ['name' => 'Ganda', 'script' => 'Latn', 'native' => 'Luganda'],
        'luy' => ['name' => 'Oluluyia', 'script' => 'Latn', 'native' => 'Luluhia'],
        'lb' => ['name' => 'Luxembourgish', 'script' => 'Latn', 'native' => 'Lëtzebuergesch'],
        'hu' => ['name' => 'Hungarian', 'script' => 'Latn', 'native' => 'Magyar'],
        'mgh' => ['name' => 'Makhuwa-Meetto', 'script' => 'Latn', 'native' => 'Makua'],
        'mg' => ['name' => 'Malagasy', 'script' => 'Latn', 'native' => 'Malagasy'],
        'mt' => ['name' => 'Maltese', 'script' => 'Latn', 'native' => 'Malti'],
        'mtr' => ['name' => 'Mewari', 'script' => 'Latn', 'native' => 'Mewari'],
        'mua' => ['name' => 'Mundang', 'script' => 'Latn', 'native' => 'Mundang'],
        'mi' => ['name' => 'Māori', 'script' => 'Latn', 'native' => 'Māori'],
        'nl' => ['name' => 'Dutch', 'script' => 'Latn', 'native' => 'Nederlands'],
        'nmg' => ['name' => 'Kwasio', 'script' => 'Latn', 'native' => 'Ngumba'],
        'yav' => ['name' => 'Yangben', 'script' => 'Latn', 'native' => 'Nuasue'],
        'nn' => ['name' => 'Norwegian Nynorsk', 'script' => 'Latn', 'native' => 'Nynorsk'],
        'oc' => ['name' => 'Occitan', 'script' => 'Latn', 'native' => 'Occitan'],
        'ang' => ['name' => 'Old English', 'script' => 'Runr', 'native' => 'Old English'],
        'xog' => ['name' => 'Soga', 'script' => 'Latn', 'native' => 'Olusoga'],
        'om' => ['name' => 'Oromo', 'script' => 'Latn', 'native' => 'Oromoo'],
        'ng' => ['name' => 'Ndonga', 'script' => 'Latn', 'native' => 'OshiNdonga'],
        'hz' => ['name' => 'Herero', 'script' => 'Latn', 'native' => 'Otjiherero'],
        'uz-Latn' => ['name' => 'Uzbek (Latin)', 'script' => 'Latn', 'native' => 'Oʼzbekcha'],
        'nds' => ['name' => 'Low German', 'script' => 'Latn', 'native' => 'Plattdüütsch'],
        'pl' => ['name' => 'Polish', 'script' => 'Latn', 'native' => 'Polski'],
        'pt' => ['name' => 'Portuguese', 'script' => 'Latn', 'native' => 'Português'],
        'pt-BR' => ['name' => 'Brazilian Portuguese', 'script' => 'Latn', 'native' => 'Português do Brasil'],
        'ff' => ['name' => 'Fulah', 'script' => 'Latn', 'native' => 'Pulaar'],
        'pi' => ['name' => 'Pahari-Potwari', 'script' => 'Latn', 'native' => 'Pāli'],
        'aa' => ['name' => 'Afar', 'script' => 'Latn', 'native' => 'Qafar'],
        'ty' => ['name' => 'Tahitian', 'script' => 'Latn', 'native' => 'Reo Māohi'],
        'ksf' => ['name' => 'Bafia', 'script' => 'Latn', 'native' => 'Rikpa'],
        'ro' => ['name' => 'Romanian', 'script' => 'Latn', 'native' => 'Română'],
        'cgg' => ['name' => 'Chiga', 'script' => 'Latn', 'native' => 'Rukiga'],
        'rm' => ['name' => 'Romansh', 'script' => 'Latn', 'native' => 'Rumantsch'],
        'qu' => ['name' => 'Quechua', 'script' => 'Latn', 'native' => 'Runa Simi'],
        'nyn' => ['name' => 'Nyankole', 'script' => 'Latn', 'native' => 'Runyankore'],
        'ssy' => ['name' => 'Saho', 'script' => 'Latn', 'native' => 'Saho'],
        'sc' => ['name' => 'Sardinian', 'script' => 'Latn', 'native' => 'Sardu'],
        'de-CH' => ['name' => 'Swiss High German', 'script' => 'Latn', 'native' => 'Schweizer Hochdeutsch'],
        'gsw' => ['name' => 'Swiss German', 'script' => 'Latn', 'native' => 'Schwiizertüütsch'],
        'trv' => ['name' => 'Taroko', 'script' => 'Latn', 'native' => 'Seediq'],
        'seh' => ['name' => 'Sena', 'script' => 'Latn', 'native' => 'Sena'],
        'nso' => ['name' => 'Northern Sotho', 'script' => 'Latn', 'native' => 'Sesotho sa Leboa'],
        'st' => ['name' => 'Southern Sotho', 'script' => 'Latn', 'native' => 'Sesotho'],
        'tn' => ['name' => 'Tswana', 'script' => 'Latn', 'native' => 'Setswana'],
        'sq' => ['name' => 'Albanian', 'script' => 'Latn', 'native' => 'Shqip'],
        'sid' => ['name' => 'Sidamo', 'script' => 'Latn', 'native' => 'Sidaamu Afo'],
        'ss' => ['name' => 'Swati', 'script' => 'Latn', 'native' => 'Siswati'],
        'sk' => ['name' => 'Slovak', 'script' => 'Latn', 'native' => 'Slovenčina'],
        'sl' => ['name' => 'Slovene', 'script' => 'Latn', 'native' => 'Slovenščina'],
        'so' => ['name' => 'Somali', 'script' => 'Latn', 'native' => 'Soomaali'],
        'sr-Latn' => ['name' => 'Serbian (Latin)', 'script' => 'Latn', 'native' => 'Srpski'],
        'sh' => ['name' => 'Serbo-Croatian', 'script' => 'Latn', 'native' => 'Srpskohrvatski'],
        'fi' => ['name' => 'Finnish', 'script' => 'Latn', 'native' => 'Suomi'],
        'sv' => ['name' => 'Swedish', 'script' => 'Latn', 'native' => 'Svenska'],
        'sg' => ['name' => 'Sango', 'script' => 'Latn', 'native' => 'Sängö'],
        'tl' => ['name' => 'Tagalog', 'script' => 'Latn', 'native' => 'Tagalog'],
        'tzm-Latn' => ['name' => 'Central Atlas Tamazight (Latin)', 'script' => 'Latn', 'native' => 'Tamazight'],
        'kab' => ['name' => 'Kabyle', 'script' => 'Latn', 'native' => 'Taqbaylit'],
        'twq' => ['name' => 'Tasawaq', 'script' => 'Latn', 'native' => 'Tasawaq senni'],
        'shi' => ['name' => 'Tachelhit (Latin)', 'script' => 'Latn', 'native' => 'Tashelhit'],
        'nus' => ['name' => 'Nuer', 'script' => 'Latn', 'native' => 'Thok Nath'],
        'vi' => ['name' => 'Vietnamese', 'script' => 'Latn', 'native' => 'Tiếng Việt', 'country_code' => 'VN'],
        'tg-Latn' => ['name' => 'Tajik (Latin)', 'script' => 'Latn', 'native' => 'Tojikī'],
        'lu' => ['name' => 'Luba-Katanga', 'script' => 'Latn', 'native' => 'Tshiluba'],
        've' => ['name' => 'Venda', 'script' => 'Latn', 'native' => 'Tshivenḓa'],
        'tw' => ['name' => 'Twi', 'script' => 'Latn', 'native' => 'Twi'],
        'tr' => ['name' => 'Turkish', 'script' => 'Latn', 'native' => 'Türkçe'],
        'ale' => ['name' => 'Aleut', 'script' => 'Latn', 'native' => 'Unangax tunuu'],
        'ca-valencia' => ['name' => 'Valencian', 'script' => 'Latn', 'native' => 'Valencià'],
        'vai-Latn' => ['name' => 'Vai (Latin)', 'script' => 'Latn', 'native' => 'Viyamíĩ'],
        'vo' => ['name' => 'Volapük', 'script' => 'Latn', 'native' => 'Volapük'],
        'fj' => ['name' => 'Fijian', 'script' => 'Latn', 'native' => 'vosa Vakaviti'],
        'wa' => ['name' => 'Walloon', 'script' => 'Latn', 'native' => 'Walon'],
        'wae' => ['name' => 'Walser', 'script' => 'Latn', 'native' => 'Walser'],
        'wen' => ['name' => 'Sorbian', 'script' => 'Latn', 'native' => 'Wendic'],
        'wo' => ['name' => 'Wolof', 'script' => 'Latn', 'native' => 'Wolof'],
        'ts' => ['name' => 'Tsonga', 'script' => 'Latn', 'native' => 'Xitsonga'],
        'dje' => ['name' => 'Zarma', 'script' => 'Latn', 'native' => 'Zarmaciine'],
        'yo' => ['name' => 'Yoruba', 'script' => 'Latn', 'native' => 'Èdè Yorùbá'],
        'de-AT' => ['name' => 'Austrian German', 'script' => 'Latn', 'native' => 'Österreichisches Deutsch'],
        'is' => ['name' => 'Icelandic', 'script' => 'Latn', 'native' => 'Íslenska'],
        'cs' => ['name' => 'Czech', 'script' => 'Latn', 'native' => 'Čeština'],
        'bas' => ['name' => 'Basa', 'script' => 'Latn', 'native' => 'Ɓàsàa'],
        'mas' => ['name' => 'Masai', 'script' => 'Latn', 'native' => 'Ɔl-Maa'],
        'haw' => ['name' => 'Hawaiian', 'script' => 'Latn', 'native' => 'ʻŌlelo Hawaiʻi'],
        'el' => ['name' => 'Greek', 'script' => 'Grek', 'native' => 'Ελληνικά'],
        'uz' => ['name' => 'Uzbek (Cyrillic)', 'script' => 'Cyrl', 'native' => 'Ўзбек'],
        'az-Cyrl' => ['name' => 'Azerbaijani (Cyrillic)', 'script' => 'Cyrl', 'native' => 'Азәрбајҹан'],
        'ab' => ['name' => 'Abkhazian', 'script' => 'Cyrl', 'native' => 'Аҧсуа'],
        'os' => ['name' => 'Ossetic', 'script' => 'Cyrl', 'native' => 'Ирон'],
        'ky' => ['name' => 'Kyrgyz', 'script' => 'Cyrl', 'native' => 'Кыргыз'],
        'sr' => ['name' => 'Serbian (Cyrillic)', 'script' => 'Cyrl', 'native' => 'Српски'],
        'av' => ['name' => 'Avaric', 'script' => 'Cyrl', 'native' => 'Aвар мацӀ'],
        'ady' => ['name' => 'Adyghe', 'script' => 'Cyrl', 'native' => 'Aдыгэбзэ'],
        'ba' => ['name' => 'Bashkir', 'script' => 'Cyrl', 'native' => 'Башҡорт теле'],
        'be' => ['name' => 'Belarusian', 'script' => 'Cyrl', 'native' => 'Беларуская'],
        'bg' => ['name' => 'Bulgarian', 'script' => 'Cyrl', 'native' => 'Български'],
        'kv' => ['name' => 'Komi', 'script' => 'Cyrl', 'native' => 'Коми кыв'],
        'mk' => ['name' => 'Macedonian', 'script' => 'Cyrl', 'native' => 'Македонски'],
        'mn' => ['name' => 'Mongolian (Cyrillic)', 'script' => 'Cyrl', 'native' => 'Монгол'],
        'ce' => ['name' => 'Chechen', 'script' => 'Cyrl', 'native' => 'Нохчийн мотт'],
        'ru' => ['name' => 'Russian', 'script' => 'Cyrl', 'native' => 'Русский'],
        'sah' => ['name' => 'Yakut', 'script' => 'Cyrl', 'native' => 'Саха тыла'],
        'tt' => ['name' => 'Tatar', 'script' => 'Cyrl', 'native' => 'Татар теле'],
        'tg' => ['name' => 'Tajik (Cyrillic)', 'script' => 'Cyrl', 'native' => 'Тоҷикӣ'],
        'tk' => ['name' => 'Turkmen', 'script' => 'Cyrl', 'native' => 'Түркменче'],
        'uk' => ['name' => 'Ukrainian', 'script' => 'Cyrl', 'native' => 'Українська'],
        'cv' => ['name' => 'Chuvash', 'script' => 'Cyrl', 'native' => 'Чӑваш чӗлхи'],
        'cu' => ['name' => 'Church Slavic', 'script' => 'Cyrl', 'native' => 'Ѩзыкъ словѣньскъ'],
        'kk' => ['name' => 'Kazakh', 'script' => 'Cyrl', 'native' => 'Қазақ тілі'],
        'hy' => ['name' => 'Armenian', 'script' => 'Armn', 'native' => 'Հայերէն'],
        'yi' => ['name' => 'Yiddish', 'script' => 'Hebr', 'native' => 'ייִדיש'],
        'he' => ['name' => 'Hebrew', 'script' => 'Hebr', 'native' => 'עברית'],
        'ug' => ['name' => 'Uyghur', 'script' => 'Arab', 'native' => 'ئۇيغۇرچە'],
        'ur' => ['name' => 'Urdu', 'script' => 'Arab', 'native' => 'اردو'],
        'ar' => ['name' => 'Arabic', 'script' => 'Arab', 'native' => 'العربية'],
        'uz-Arab' => ['name' => 'Uzbek (Arabic)', 'script' => 'Arab', 'native' => 'اۉزبېک'],
        'tg-Arab' => ['name' => 'Tajik (Arabic)', 'script' => 'Arab', 'native' => 'تاجیکی'],
        'sd' => ['name' => 'Sindhi', 'script' => 'Arab', 'native' => 'سنڌي'],
        'fa' => ['name' => 'Persian', 'script' => 'Arab', 'native' => 'فارسی'],
        'pa-Arab' => ['name' => 'Punjabi (Arabic)', 'script' => 'Arab', 'native' => 'پنجاب'],
        'ps' => ['name' => 'Pashto', 'script' => 'Arab', 'native' => 'پښتو'],
        'ks' => ['name' => 'Kashmiri (Arabic)', 'script' => 'Arab', 'native' => 'کأشُر'],
        'ku' => ['name' => 'Kurdish', 'script' => 'Arab', 'native' => 'کوردی'],
        'dv' => ['name' => 'Divehi', 'script' => 'Thaa', 'native' => 'ދިވެހިބަސް'],
        'ks-Deva' => ['name' => 'Kashmiri (Devaganari)', 'script' => 'Deva', 'native' => 'कॉशुर'],
        'kok' => ['name' => 'Konkani', 'script' => 'Deva', 'native' => 'कोंकणी'],
        'doi' => ['name' => 'Dogri', 'script' => 'Deva', 'native' => 'डोगरी'],
        'ne' => ['name' => 'Nepali', 'script' => 'Deva', 'native' => 'नेपाली'],
        'pra' => ['name' => 'Prakrit', 'script' => 'Deva', 'native' => 'प्राकृत'],
        'brx' => ['name' => 'Bodo', 'script' => 'Deva', 'native' => 'बड़ो'],
        'bra' => ['name' => 'Braj', 'script' => 'Deva', 'native' => 'ब्रज भाषा'],
        'mr' => ['name' => 'Marathi', 'script' => 'Deva', 'native' => 'मराठी'],
        'mai' => ['name' => 'Maithili', 'script' => 'Tirh', 'native' => 'मैथिली'],
        'raj' => ['name' => 'Rajasthani', 'script' => 'Deva', 'native' => 'राजस्थानी'],
        'sa' => ['name' => 'Sanskrit', 'script' => 'Deva', 'native' => 'संस्कृतम्'],
        'hi' => ['name' => 'Hindi', 'script' => 'Deva', 'native' => 'हिन्दी'],
        'as' => ['name' => 'Assamese', 'script' => 'Beng', 'native' => 'অসমীয়া'],
        'bn' => ['name' => 'Bengali', 'script' => 'Beng', 'native' => 'বাংলা'],
        'mni' => ['name' => 'Manipuri', 'script' => 'Beng', 'native' => 'মৈতৈ'],
        'pa' => ['name' => 'Punjabi (Gurmukhi)', 'script' => 'Guru', 'native' => 'ਪੰਜਾਬੀ'],
        'gu' => ['name' => 'Gujarati', 'script' => 'Gujr', 'native' => 'ગુજરાતી'],
        'or' => ['name' => 'Oriya', 'script' => 'Orya', 'native' => 'ଓଡ଼ିଆ'],
        'ta' => ['name' => 'Tamil', 'script' => 'Taml', 'native' => 'தமிழ்'],
        'te' => ['name' => 'Telugu', 'script' => 'Telu', 'native' => 'తెలుగు'],
        'kn' => ['name' => 'Kannada', 'script' => 'Knda', 'native' => 'ಕನ್ನಡ'],
        'ml' => ['name' => 'Malayalam', 'script' => 'Mlym', 'native' => 'മലയാളം'],
        'si' => ['name' => 'Sinhala', 'script' => 'Sinh', 'native' => 'සිංහල'],
        'th' => ['name' => 'Thai', 'script' => 'Thai', 'native' => 'ไทย'],
        'lo' => ['name' => 'Lao', 'script' => 'Laoo', 'native' => 'ລາວ'],
        'bo' => ['name' => 'Tibetan', 'script' => 'Tibt', 'native' => 'པོད་སྐད་'],
        'dz' => ['name' => 'Dzongkha', 'script' => 'Tibt', 'native' => 'རྫོང་ཁ'],
        'my' => ['name' => 'Burmese', 'script' => 'Mymr', 'native' => 'မြန်မာဘာသာ'],
        'ka' => ['name' => 'Georgian', 'script' => 'Geor', 'native' => 'ქართული'],
        'byn' => ['name' => 'Blin', 'script' => 'Ethi', 'native' => 'ብሊን'],
        'tig' => ['name' => 'Tigre', 'script' => 'Ethi', 'native' => 'ትግረ'],
        'ti' => ['name' => 'Tigrinya', 'script' => 'Ethi', 'native' => 'ትግርኛ'],
        'am' => ['name' => 'Amharic', 'script' => 'Ethi', 'native' => 'አማርኛ'],
        'wal' => ['name' => 'Wolaytta', 'script' => 'Ethi', 'native' => 'ወላይታቱ'],
        'chr' => ['name' => 'Cherokee', 'script' => 'Cher', 'native' => 'ᏣᎳᎩ'],
        'iu' => ['name' => 'Inuktitut (Canadian Aboriginal Syllabics)', 'script' => 'Cans', 'native' => 'ᐃᓄᒃᑎᑐᑦ'],
        'oj' => ['name' => 'Ojibwa', 'script' => 'Cans', 'native' => 'ᐊᓂᔑᓈᐯᒧᐎᓐ'],
        'cr' => ['name' => 'Cree', 'script' => 'Cans', 'native' => 'ᓀᐦᐃᔭᐍᐏᐣ'],
        'km' => ['name' => 'Khmer', 'script' => 'Khmr', 'native' => 'ភាសាខ្មែរ'],
        'mn-Mong' => ['name' => 'Mongolian (Mongolian)', 'script' => 'Mong', 'native' => 'ᠮᠣᠨᠭᠭᠣᠯ ᠬᠡᠯᠡ'],
        'shi-Tfng' => ['name' => 'Tachelhit (Tifinagh)', 'script' => 'Tfng', 'native' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ'],
        'tzm' => ['name' => 'Central Atlas Tamazight (Tifinagh)', 'script' => 'Tfng', 'native' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ'],
        'yue' => ['name' => 'Yue', 'script' => 'Hant', 'native' => '廣州話'],
        'ja' => ['name' => 'Japanese', 'script' => 'Jpan', 'native' => '日本語'],
        'zh' => ['name' => 'Chinese (Simplified)', 'script' => 'Hans', 'native' => '简体中文'],
        'zh-Hant' => ['name' => 'Chinese (Traditional)', 'script' => 'Hant', 'native' => '繁體中文'],
        'ii' => ['name' => 'Sichuan Yi', 'script' => 'Yiii', 'native' => 'ꆈꌠꉙ'],
        'vai' => ['name' => 'Vai (Vai)', 'script' => 'Vaii', 'native' => 'ꕙꔤ'],
        'jv-Java' => ['name' => 'Javanese (Javanese)', 'script' => 'Java', 'native' => 'ꦧꦱꦗꦮ'],
        'ko' => ['name' => 'Korean', 'script' => 'Hang', 'native' => '한국어'],
    ],

    'countries' => [
        'AF' => ['name' => 'Afghanistan (‫افغانستان‬‎)', 'calling_code' => '93'],
        'AX' => ['name' => 'Åland Islands (Åland)', 'calling_code' => '358'],
        'AL' => ['name' => 'Albania (Shqipëri)', 'calling_code' => '355'],
        'DZ' => ['name' => 'Algeria (‫الجزائر‬‎)', 'calling_code' => '213'],
        'AS' => ['name' => 'American Samoa', 'calling_code' => '1'],
        'AD' => ['name' => 'Andorra', 'calling_code' => '376'],
        'AO' => ['name' => 'Angola', 'calling_code' => '244'],
        'AI' => ['name' => 'Anguilla', 'calling_code' => '1'],
        'AQ' => ['name' => 'Antarctica', 'calling_code' => ''],
        'AG' => ['name' => 'Antigua and Barbuda', 'calling_code' => '1'],
        'AR' => ['name' => 'Argentina', 'calling_code' => '54'],
        'AM' => ['name' => 'Armenia (Հայաստան)', 'calling_code' => '374'],
        'AW' => ['name' => 'Aruba', 'calling_code' => '297'],
        'AC' => ['name' => 'Ascension Island', 'calling_code' => '247'],
        'AU' => ['name' => 'Australia', 'calling_code' => '61'],
        'AT' => ['name' => 'Austria (Österreich)', 'calling_code' => '43'],
        'AZ' => ['name' => 'Azerbaijan (Azərbaycan)', 'calling_code' => '994'],
        'BS' => ['name' => 'Bahamas', 'calling_code' => '1'],
        'BH' => ['name' => 'Bahrain (‫البحرين‬‎)', 'calling_code' => '973'],
        'BD' => ['name' => 'Bangladesh (বাংলাদেশ)', 'calling_code' => '880'],
        'BB' => ['name' => 'Barbados', 'calling_code' => '1'],
        'BY' => ['name' => 'Belarus (Беларусь)', 'calling_code' => '375'],
        'BE' => ['name' => 'Belgium (België)', 'calling_code' => '32'],
        'BZ' => ['name' => 'Belize', 'calling_code' => '501'],
        'BJ' => ['name' => 'Benin (Bénin)', 'calling_code' => '229'],
        'BM' => ['name' => 'Bermuda', 'calling_code' => '1'],
        'BT' => ['name' => 'Bhutan (འབྲུག)', 'calling_code' => '975'],
        'BO' => ['name' => 'Bolivia', 'calling_code' => '591'],
        'BQ' => ['name' => 'Bonaire, Sint Eustatius and Saba', 'calling_code' => '599'],
        'BA' => ['name' => 'Bosnia and Herzegovina (Босна и Херцеговина)', 'calling_code' => '387'],
        'BW' => ['name' => 'Botswana', 'calling_code' => '267'],
        'BV' => ['name' => 'Bouvet Island', 'calling_code' => '47'],
        'BR' => ['name' => 'Brazil (Brasil)', 'calling_code' => '55'],
        'IO' => ['name' => 'British Indian Ocean Territory', 'calling_code' => '246'],
        'VG' => ['name' => 'British Virgin Islands', 'calling_code' => '1'],
        'BN' => ['name' => 'Brunei Darussalam', 'calling_code' => '673'],
        'BG' => ['name' => 'Bulgaria (България)', 'calling_code' => '359'],
        'BF' => ['name' => 'Burkina Faso', 'calling_code' => '226'],
        'BI' => ['name' => 'Burundi (Uburundi)', 'calling_code' => '257'],
        'KH' => ['name' => 'Cambodia (កម្ពុជា)', 'calling_code' => '855'],
        'CM' => ['name' => 'Cameroon (Cameroun)', 'calling_code' => '237'],
        'CA' => ['name' => 'Canada', 'calling_code' => '1'],
        'IC' => ['name' => 'Canary Islands (islas Canarias)', 'calling_code' => '34'],
        'CV' => ['name' => 'Cape Verde (Kabu Verdi)', 'calling_code' => '238'],
        'KY' => ['name' => 'Cayman Islands', 'calling_code' => '1'],
        'CF' => ['name' => 'Central African Republic (République centrafricaine)', 'calling_code' => '236'],
        'EA' => ['name' => 'Ceuta and Melilla (Ceuta y Melilla)', 'calling_code' => '34'],
        'TD' => ['name' => 'Chad (Tchad)', 'calling_code' => '235'],
        'CL' => ['name' => 'Chile', 'calling_code' => '56'],
        'CN' => ['name' => 'China (中国)', 'calling_code' => '86'],
        'CX' => ['name' => 'Christmas Island', 'calling_code' => '61'],
        'CP' => ['name' => 'Clipperton Island', 'calling_code' => ''],
        'CC' => ['name' => 'Cocos (Keeling) Islands (Kepulauan Cocos (Keeling))', 'calling_code' => '61'],
        'CO' => ['name' => 'Colombia', 'calling_code' => '57'],
        'KM' => ['name' => 'Comoros (‫جزر القمر‬‎)', 'calling_code' => '269'],
        'CD' => ['name' => 'Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)', 'calling_code' => '243'],
        'CG' => ['name' => 'Congo (Republic) (Congo-Brazzaville)', 'calling_code' => '242'],
        'CK' => ['name' => 'Cook Islands', 'calling_code' => '682'],
        'CR' => ['name' => 'Costa Rica', 'calling_code' => '506'],
        'CI' => ['name' => 'Côte d’Ivoire', 'calling_code' => '225'],
        'HR' => ['name' => 'Croatia (Hrvatska)', 'calling_code' => '385'],
        'CU' => ['name' => 'Cuba', 'calling_code' => '53'],
        'CW' => ['name' => 'Curaçao', 'calling_code' => '599'],
        'CY' => ['name' => 'Cyprus (Κύπρος)', 'calling_code' => '357'],
        'CZ' => ['name' => 'Czech Republic (Česká republika)', 'calling_code' => '420'],
        'DK' => ['name' => 'Denmark (Danmark)', 'calling_code' => '45'],
        'DG' => ['name' => 'Diego Garcia', 'calling_code' => '246'],
        'DJ' => ['name' => 'Djibouti', 'calling_code' => '253'],
        'DM' => ['name' => 'Dominica', 'calling_code' => '1'],
        'DO' => ['name' => 'Dominican Republic (República Dominicana)', 'calling_code' => '1'],
        'EC' => ['name' => 'Ecuador', 'calling_code' => '593'],
        'EG' => ['name' => 'Egypt (‫مصر‬‎)', 'calling_code' => '20'],
        'SV' => ['name' => 'El Salvador', 'calling_code' => '503'],
        'GQ' => ['name' => 'Equatorial Guinea (Guinea Ecuatorial)', 'calling_code' => '249'],
        'ER' => ['name' => 'Eritrea', 'calling_code' => '291'],
        'EE' => ['name' => 'Estonia (Eesti)', 'calling_code' => '372'],
        'ET' => ['name' => 'Ethiopia', 'calling_code' => '251'],
        'FK' => ['name' => 'Falkland Islands (Islas Malvinas)', 'calling_code' => '500'],
        'FO' => ['name' => 'Faroe Islands (Føroyar)', 'calling_code' => '298'],
        'FJ' => ['name' => 'Fiji', 'calling_code' => '679'],
        'FI' => ['name' => 'Finland (Suomi)', 'calling_code' => '358'],
        'FR' => ['name' => 'France', 'calling_code' => '33'],
        'GF' => ['name' => 'French Guiana (Guyane française)', 'calling_code' => '594'],
        'PF' => ['name' => 'French Polynesia (Polynésie française)', 'calling_code' => '689'],
        'TF' => ['name' => 'French Southern Territories (Terres australes françaises)', 'calling_code' => '262'],
        'GA' => ['name' => 'Gabon', 'calling_code' => '241'],
        'GM' => ['name' => 'Gambia', 'calling_code' => '220'],
        'GE' => ['name' => 'Georgia (საქართველო)', 'calling_code' => '995'],
        'DE' => ['name' => 'Germany (Deutschland)', 'calling_code' => '49'],
        'GH' => ['name' => 'Ghana (Gaana)', 'calling_code' => '233'],
        'GI' => ['name' => 'Gibraltar', 'calling_code' => '350'],
        'GR' => ['name' => 'Greece (Ελλάδα)', 'calling_code' => '30'],
        'GL' => ['name' => 'Greenland (Kalaallit Nunaat)', 'calling_code' => '299'],
        'GD' => ['name' => 'Grenada', 'calling_code' => '1'],
        'GP' => ['name' => 'Guadeloupe', 'calling_code' => '590'],
        'GU' => ['name' => 'Guam', 'calling_code' => '1'],
        'GT' => ['name' => 'Guatemala', 'calling_code' => '502'],
        'GG' => ['name' => 'Guernsey', 'calling_code' => '44'],
        'GN' => ['name' => 'Guinea (Guinée)', 'calling_code' => '224'],
        'GW' => ['name' => 'Guinea-Bissau (Guiné Bissau)', 'calling_code' => '245'],
        'GY' => ['name' => 'Guyana', 'calling_code' => '592'],
        'HT' => ['name' => 'Haiti', 'calling_code' => '509'],
        'HM' => ['name' => 'Heard Island and McDonald Islands', 'calling_code' => ''],
        'HN' => ['name' => 'Honduras', 'calling_code' => '504'],
        'HK' => ['name' => 'Hong Kong (香港)', 'calling_code' => '852'],
        'HU' => ['name' => 'Hungary (Magyarország)', 'calling_code' => '36'],
        'IS' => ['name' => 'Iceland (Ísland)', 'calling_code' => '354'],
        'IN' => ['name' => 'India (भारत)', 'calling_code' => '91'],
        'ID' => ['name' => 'Indonesia', 'calling_code' => '62'],
        'IR' => ['name' => 'Iran (‫ایران‬‎)', 'calling_code' => '98'],
        'IQ' => ['name' => 'Iraq (‫العراق‬‎)', 'calling_code' => '964'],
        'IE' => ['name' => 'Ireland', 'calling_code' => '353'],
        'IM' => ['name' => 'Isle of Man', 'calling_code' => '44'],
        'IL' => ['name' => 'Israel (‫ישראל‬‎)', 'calling_code' => '972'],
        'IT' => ['name' => 'Italy (Italia)', 'calling_code' => '39'],
        'JM' => ['name' => 'Jamaica', 'calling_code' => '1'],
        'JP' => ['name' => 'Japan (日本)', 'calling_code' => '81'],
        'JE' => ['name' => 'Jersey', 'calling_code' => '44'],
        'JO' => ['name' => 'Jordan (‫الأردن‬‎)', 'calling_code' => '962'],
        'KZ' => ['name' => 'Kazakhstan (Казахстан)', 'calling_code' => '7'],
        'KE' => ['name' => 'Kenya', 'calling_code' => '254'],
        'KI' => ['name' => 'Kiribati', 'calling_code' => '686'],
        'KP' => ['name' => 'North Korea (조선 민주주의 인민 공화국)', 'calling_code' => '850'],
        'KR' => ['name' => 'South Korea (대한민국)', 'calling_code' => '82'],
        'XK' => ['name' => 'Kosovo (Kosovë)', 'calling_code' => '381'],
        'KW' => ['name' => 'Kuwait (‫الكويت‬‎)', 'calling_code' => '965'],
        'KG' => ['name' => 'Kyrgyzstan (Кыргызстан)', 'calling_code' => '996'],
        'LA' => ['name' => 'Laos (ລາວ)', 'calling_code' => '856'],
        'LV' => ['name' => 'Latvia (Latvija)', 'calling_code' => '371'],
        'LB' => ['name' => 'Lebanon (‫لبنان‬‎)', 'calling_code' => '961'],
        'LS' => ['name' => 'Lesotho', 'calling_code' => '266'],
        'LR' => ['name' => 'Liberia', 'calling_code' => '231'],
        'LY' => ['name' => 'Libya (‫ليبيا‬‎)', 'calling_code' => '218'],
        'LI' => ['name' => 'Liechtenstein', 'calling_code' => '423'],
        'LT' => ['name' => 'Lithuania (Lietuva)', 'calling_code' => '370'],
        'LU' => ['name' => 'Luxembourg', 'calling_code' => '352'],
        'MO' => ['name' => 'Macao (澳門)', 'calling_code' => '853'],
        'MK' => ['name' => 'Macedonia (FYROM) (Македонија)', 'calling_code' => '389'],
        'MG' => ['name' => 'Madagascar (Madagasikara)', 'calling_code' => '261'],
        'MW' => ['name' => 'Malawi', 'calling_code' => '265'],
        'MY' => ['name' => 'Malaysia', 'calling_code' => '60'],
        'MV' => ['name' => 'Maldives', 'calling_code' => '960'],
        'ML' => ['name' => 'Mali', 'calling_code' => '223'],
        'MT' => ['name' => 'Malta', 'calling_code' => '356'],
        'MH' => ['name' => 'Marshall Islands', 'calling_code' => '692'],
        'MQ' => ['name' => 'Martinique', 'calling_code' => '596'],
        'MR' => ['name' => 'Mauritania (‫موريتانيا‬‎)', 'calling_code' => '222'],
        'MU' => ['name' => 'Mauritius (Moris)', 'calling_code' => '230'],
        'YT' => ['name' => 'Mayotte', 'calling_code' => '262'],
        'MX' => ['name' => 'Mexico (México)', 'calling_code' => '52'],
        'FM' => ['name' => 'Federated States of Micronesia', 'calling_code' => '691'],
        'MD' => ['name' => 'Moldova (Republica Moldova)', 'calling_code' => '373'],
        'MC' => ['name' => 'Monaco', 'calling_code' => '377'],
        'MN' => ['name' => 'Mongolia (Монгол)', 'calling_code' => '976'],
        'ME' => ['name' => 'Montenegro (Crna Gora)', 'calling_code' => '382'],
        'MS' => ['name' => 'Montserrat', 'calling_code' => '1'],
        'MA' => ['name' => 'Morocco (‫المغرب‬‎)', 'calling_code' => '212'],
        'MZ' => ['name' => 'Mozambique (Moçambique)', 'calling_code' => '258'],
        'MM' => ['name' => 'Myanmar (Burma) (မြန်မာ)', 'calling_code' => '95'],
        'NA' => ['name' => 'Namibia (Namibië)', 'calling_code' => '264'],
        'NR' => ['name' => 'Nauru', 'calling_code' => '674'],
        'NP' => ['name' => 'Nepal (नेपाल)', 'calling_code' => '977'],
        'NL' => ['name' => 'Netherlands (Nederland)', 'calling_code' => '31'],
        'NC' => ['name' => 'New Caledonia (Nouvelle-Calédonie)', 'calling_code' => '687'],
        'NZ' => ['name' => 'New Zealand', 'calling_code' => '64'],
        'NI' => ['name' => 'Nicaragua', 'calling_code' => '505'],
        'NE' => ['name' => 'Niger (Nijar)', 'calling_code' => '227'],
        'NG' => ['name' => 'Nigeria', 'calling_code' => '234'],
        'NU' => ['name' => 'Niue', 'calling_code' => '683'],
        'NF' => ['name' => 'Norfolk Island', 'calling_code' => '672'],
        'MP' => ['name' => 'Northern Mariana Islands', 'calling_code' => '1'],
        'NO' => ['name' => 'Norway (Norge)', 'calling_code' => '47'],
        'OM' => ['name' => 'Oman (‫عُمان‬‎)', 'calling_code' => '968'],
        'PK' => ['name' => 'Pakistan (‫پاکستان‬‎)', 'calling_code' => '92'],
        'PW' => ['name' => 'Palau', 'calling_code' => '680'],
        'PS' => ['name' => 'Palestine (‫فلسطين‬‎)', 'calling_code' => '970'],
        'PA' => ['name' => 'Panama (Panamá)', 'calling_code' => '507'],
        'PG' => ['name' => 'Papua New Guinea', 'calling_code' => '675'],
        'PY' => ['name' => 'Paraguay', 'calling_code' => '595'],
        'PE' => ['name' => 'Peru (Perú)', 'calling_code' => '51'],
        'PH' => ['name' => 'Philippines', 'calling_code' => '63'],
        'PN' => ['name' => 'Pitcairn Islands', 'calling_code' => '64'],
        'PL' => ['name' => 'Poland (Polska)', 'calling_code' => '48'],
        'PT' => ['name' => 'Portugal', 'calling_code' => '351'],
        'PR' => ['name' => 'Puerto Rico', 'calling_code' => '1'],
        'QA' => ['name' => 'Qatar (‫قطر‬‎)', 'calling_code' => '974'],
        'RE' => ['name' => 'Réunion (La Réunion)', 'calling_code' => '262'],
        'RO' => ['name' => 'Romania (România)', 'calling_code' => '40'],
        'RU' => ['name' => 'Russia (Россия)', 'calling_code' => '7'],
        'RW' => ['name' => 'Rwanda', 'calling_code' => '250'],
        'BL' => ['name' => 'Saint Barthélemy (Saint-Barthélemy)', 'calling_code' => '590'],
        'SH' => ['name' => 'Saint Helena', 'calling_code' => '290'],
        'KN' => ['name' => 'Saint Kitts and Nevis', 'calling_code' => '1'],
        'LC' => ['name' => 'Saint Lucia', 'calling_code' => '1'],
        'MF' => ['name' => 'Saint Martin (Saint-Martin (partie française))', 'calling_code' => '590'],
        'PM' => ['name' => 'Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)', 'calling_code' => '508'],
        'VC' => ['name' => 'Saint Vincent and Grenadines', 'calling_code' => '1'],
        'WS' => ['name' => 'Samoa', 'calling_code' => '685'],
        'SM' => ['name' => 'San Marino', 'calling_code' => '378'],
        'ST' => ['name' => 'São Tomé and Príncipe (São Tomé e Príncipe)', 'calling_code' => '239'],
        'SA' => ['name' => 'Saudi Arabia (‫المملكة العربية السعودية‬‎)', 'calling_code' => '966'],
        'SN' => ['name' => 'Senegal (Sénégal)', 'calling_code' => '221'],
        'RS' => ['name' => 'Serbia (Србија)', 'calling_code' => '381'],
        'SC' => ['name' => 'Seychelles', 'calling_code' => '248'],
        'SL' => ['name' => 'Sierra Leone', 'calling_code' => '232'],
        'SG' => ['name' => 'Singapore', 'calling_code' => '65'],
        'SX' => ['name' => 'Sint Maarten', 'calling_code' => '599'],
        'SK' => ['name' => 'Slovakia (Slovensko)', 'calling_code' => '421'],
        'SI' => ['name' => 'Slovenia (Slovenija)', 'calling_code' => '386'],
        'SB' => ['name' => 'Solomon Islands', 'calling_code' => '677'],
        'SO' => ['name' => 'Somalia (Soomaaliya)', 'calling_code' => '252'],
        'ZA' => ['name' => 'South Africa', 'calling_code' => '27'],
        'GS' => ['name' => 'South Georgia and South Sandwich Islands', 'calling_code' => '500'],
        'SS' => ['name' => 'South Sudan (‫جنوب السودان‬‎)', 'calling_code' => '211'],
        'ES' => ['name' => 'Spain (España)', 'calling_code' => '34'],
        'LK' => ['name' => 'Sri Lanka (ශ්‍රී ලංකාව)', 'calling_code' => '94'],
        'SD' => ['name' => 'Sudan (‫السودان‬‎)', 'calling_code' => '249'],
        'SR' => ['name' => 'Suriname', 'calling_code' => '597'],
        'SJ' => ['name' => 'Svalbard and Jan Mayen (Svalbard og Jan Mayen)', 'calling_code' => '47'],
        'SZ' => ['name' => 'Swaziland', 'calling_code' => '268'],
        'SE' => ['name' => 'Sweden (Sverige)', 'calling_code' => '46'],
        'CH' => ['name' => 'Switzerland (Schweiz)', 'calling_code' => '41'],
        'SY' => ['name' => 'Syria (‫سوريا‬‎)', 'calling_code' => '963'],
        'TW' => ['name' => 'Taiwan (台灣)', 'calling_code' => '886'],
        'TJ' => ['name' => 'Tajikistan', 'calling_code' => '992'],
        'TZ' => ['name' => 'Tanzania', 'calling_code' => '255'],
        'TH' => ['name' => 'Thailand (ไทย)', 'calling_code' => '66'],
        'TL' => ['name' => 'Timor-Leste', 'calling_code' => '670'],
        'TG' => ['name' => 'Togo', 'calling_code' => '228'],
        'TK' => ['name' => 'Tokelau', 'calling_code' => '690'],
        'TO' => ['name' => 'Tonga', 'calling_code' => '676'],
        'TT' => ['name' => 'Trinidad and Tobago', 'calling_code' => '1'],
        'TA' => ['name' => 'Tristan da Cunha', 'calling_code' => '290'],
        'TN' => ['name' => 'Tunisia (‫تونس‬‎)', 'calling_code' => '216'],
        'TR' => ['name' => 'Turkey (Türkiye)', 'calling_code' => '90'],
        'TM' => ['name' => 'Turkmenistan', 'calling_code' => '993'],
        'TC' => ['name' => 'Turks and Caicos Islands', 'calling_code' => '1'],
        'TV' => ['name' => 'Tuvalu', 'calling_code' => '688'],
        'UG' => ['name' => 'Uganda', 'calling_code' => '256'],
        'UA' => ['name' => 'Ukraine (Україна)', 'calling_code' => '380'],
        'AE' => ['name' => 'United Arab Emirates (‫الإمارات العربية المتحدة‬‎)', 'calling_code' => '971'],
        'GB' => ['name' => 'United Kingdom', 'calling_code' => '44'],
        'US' => ['name' => 'United States', 'calling_code' => '1'],
        'UM' => ['name' => 'U.S. Outlying Islands', 'calling_code' => '1'],
        'VI' => ['name' => 'U.S. Virgin Islands', 'calling_code' => '1'],
        'UY' => ['name' => 'Uruguay', 'calling_code' => '598'],
        'UZ' => ['name' => 'Uzbekistan (Oʻzbekiston)', 'calling_code' => '998'],
        'VU' => ['name' => 'Vanuatu', 'calling_code' => '678'],
        'VA' => ['name' => 'Vatican City (Città del Vaticano)', 'calling_code' => '39'],
        'VE' => ['name' => 'Venezuela', 'calling_code' => '58'],
        'VN' => ['name' => 'Vietnam (Việt Nam)', 'calling_code' => '84'],
        'WF' => ['name' => 'Wallis and Futuna', 'calling_code' => '681'],
        'EH' => ['name' => 'Western Sahara (‫الصحراء الغربية‬‎)', 'calling_code' => '212'],
        'YE' => ['name' => 'Yemen (‫اليمن‬‎)', 'calling_code' => '967'],
        'ZM' => ['name' => 'Zambia', 'calling_code' => '260'],
        'ZW' => ['name' => 'Zimbabwe', 'calling_code' => '263'],
    ],

    'external_links' => [
        'jquery' => 'http://code.jquery.com/jquery-2.1.4.min.js',
        'jquery-ui' => 'https://code.jquery.com/ui/1.11.4/jquery-ui.min.js',
        'jquery-ui-bootstrap' => '$.widget.bridge(\'uibutton\', $.ui.button); // Resolve conflict in jQuery UI tooltip with Bootstrap tooltip',
        'bootstrap' => 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js',
        'bootstrap-css' => 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css',
        'font-awesome-css' => 'https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css',
        'source-sans-pro-css' => 'https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,400italic,600,600italic,700,700italic,300italic,300&subset=latin,vietnamese,latin-ext',
    ],
];