<?php
/**
 * Created by PhpStorm.
 * User: Nguyen Tuan Linh
 * Date: 2016-08-26
 * Time: 20:19
 */

namespace Katniss\Everdeen\Http\Controllers;

use Katniss\Everdeen\Http\Request;

class WebApiController extends KatnissController
{
    use ApiResponseTrait;

    public function __construct()
    {
        parent::__construct();

        $this->middleware('theme')->only('extra');
    }

    public function extra(Request $request)
    {
        return parent::extra($request); // TODO: Change the autogenerated stub
    }
}